"""Member storage backed by data/members.json.

On first load, if data/members.json does not exist, it is created from
data/members.js using a Node.js subprocess. The JS file uses unquoted object
keys (window.MEMBERS = [...]) so we eval() it inside a minimal node context.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
MEMBERS_JSON = ROOT / "data" / "members.json"
MEMBERS_JS = ROOT / "data" / "members.js"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _bootstrap_from_js() -> None:
    """Create members.json from members.js using node eval."""
    script = (
        "var window={}; "
        "eval(require('fs').readFileSync(process.argv[1],'utf8')); "
        "require('fs').writeFileSync(process.argv[2], JSON.stringify(window.MEMBERS, null, 2))"
    )
    subprocess.run(
        ["node", "-e", script, str(MEMBERS_JS), str(MEMBERS_JSON)],
        check=True,
        capture_output=True,
    )


def _write_members_js(data: list) -> None:
    """Regenerate data/members.js from the given members list."""
    header = (
        "/**\n"
        " * Auto-generated by members_store.py — do not edit manually.\n"
        " * Edit via /api/admin/members endpoints instead.\n"
        " */\n"
    )
    js_body = "window.MEMBERS = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    MEMBERS_JS.write_text(header + js_body, encoding="utf-8")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_members() -> list:
    """Return all members. Creates members.json from members.js if needed."""
    if not MEMBERS_JSON.exists():
        if MEMBERS_JS.exists():
            _bootstrap_from_js()
        else:
            return []
    return json.loads(MEMBERS_JSON.read_text(encoding="utf-8"))


def save_members(data: list) -> None:
    """Persist members to members.json and regenerate members.js."""
    MEMBERS_JSON.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    _write_members_js(data)


def get_member(member_id: str) -> dict | None:
    """Return the member with the given id, or None."""
    return next((m for m in load_members() if m.get("id") == member_id), None)


def add_member(member: dict) -> dict:
    """Append a new member. member dict must include an 'id' field."""
    if not member.get("id"):
        raise ValueError("member must have an 'id' field")
    members = load_members()
    members.append(member)
    save_members(members)
    return member


def update_member(member_id: str, updates: dict) -> dict | None:
    """Apply updates to the member with the given id. Returns updated dict or None."""
    members = load_members()
    for i, m in enumerate(members):
        if m.get("id") == member_id:
            members[i] = {**m, **updates, "id": member_id}
            save_members(members)
            return members[i]
    return None


def delete_member(member_id: str) -> bool:
    """Remove the member with the given id. Returns True if removed, False if not found."""
    members = load_members()
    filtered = [m for m in members if m.get("id") != member_id]
    if len(filtered) == len(members):
        return False
    save_members(filtered)
    return True
